export const TEAM_IDS_NAMES = [
    {teamId: 1, fullName: "Atlanta Hawks"},
    {teamId: 2, fullName: "Boston Celtics"},
    {teamId: 4, fullName: "Brooklyn Nets"},
    {teamId: 5, fullName: "Charlotte Hornets"},
    {teamId: 6, fullName: "Chicago Bulls"},
    {teamId: 7, fullName: "Cleveland Cavaliers"},
    {teamId: 8, fullName: "Dallas Mavericks"},
    {teamId: 9, fullName: "Denver Nuggets"},
    {teamId: 10, fullName: "Detroit Pistons"},
    {teamId: 11, fullName: "Golden State Warriors"},
    {teamId: 14, fullName: "Houston Rockets"},
    {teamId: 15, fullName: "Indiana Pacers"},
    {teamId: 16, fullName: "LA Clippers"},
    {teamId: 17, fullName: "Los Angeles Lakers"},
    {teamId: 19, fullName: "Memphis Grizzlies"},
    {teamId: 20, fullName: "Miami Heat"},
    {teamId: 21, fullName: "Milwaukee Bucks"},
    {teamId: 22, fullName: "Minnesota Timberwolves"},
    {teamId: 23, fullName: "New Orleans Pelicans"},
    {teamId: 24, fullName: "New York Knicks"},
    {teamId: 25, fullName: "Oklahoma City Thunder"},
    {teamId: 26, fullName: "Orlando Magic"},
    {teamId: 27, fullName: "Philadelphia 76ers"},
    {teamId: 28, fullName: "Pheonix Suns"},
    {teamId: 29, fullName: "Portland Trail Blazers"},
    {teamId: 30, fullName: "Sacremento Kings"},
    {teamId: 31, fullName: "San Antonio Spurs"},
    {teamId: 38, fullName: "Toronto Raptors"},
    {teamId: 40, fullName: "Utah Jazz"},
    {teamId: 41, fullName: "Washington Wizards"},
]